
[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 1.0
blur=true

option_as_alt = "Both"

startup_mode = "Maximized"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14

[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
